name: CI Security Scanning (SAST & SCA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Run SAST and SCA Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Modern SonarQube Scan with hardcoded parameters for debugging
      - name: SonarQube Scan (SAST)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.host.url="http://34.148.24.144:9000" \
            -Dsonar.token="sqa_988c64a7f44406fb931de6acf58bb4c207b4083b" \
            -Dsonar.projectKey=gitops-sec-demo \
            -Dsonar.projectName=gitops-sec-demo \
            -Dsonar.sources=.

      # 2. Local SCA & IaC Scan via Trivy
      - name: Run Trivy Code SCA & Manifest Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,misconfig'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
