name: CI Security Scanning (SAST & SCA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Run SAST and SCA Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. SAST Scan via your Self-Hosted GKE SonarQube with Explicit Project Key
      - name: SonarQube Scan (SAST)
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=gitops-sec-demo
            -Dsonar.projectName=gitops-sec-demo

      # 2. Local SCA & IaC Scan via Trivy
      - name: Run Trivy Code SCA & Manifest Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'vuln,secret,misconfig'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
